version: 2
formats: all
conda:
  environment: environment.yml

python:
  version: "3.8"
  install:
    - requirements: requirements.txt
  system_packages: true

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false