version: 2
formats: all
python:
  version: "3.8"
  install:
    - requirements: requirements.txt
    - method: pip
    - path: ./instrumentserver
  system_packages: true

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false