name: read_the_docs
channels:
  - conda-forge
dependencies:
  - pip
  - qtpy
  - pyqt
  - pyqtgraph
  - pip:
    - ipykernel
    - nbsphinx
    - qcodes
    - pandas
    - bokeh
    - numpy
    - scipy
